### Get average national hospital capacity by month, and add that data to the main clean_data frame

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Data/clean_data.csv')
cap = pd.read_csv('Data/hospital_occupancy.csv', index_col = False)

In [3]:
cap

    adult_icu_bed_covid_utilization  inpatient_beds_utilization
0                          0.000000                    0.424642
1                               NaN                    0.461779
2                               NaN                    0.518818
3                          0.076896                    0.510773
4                               NaN                    0.600794
5                               NaN                    0.637689
6                          0.165340                    0.664927
7                          0.151257                    0.663529
8                          0.116432                    0.661602
9                          0.139070                    0.680998
10                         0.229720                    0.688734
11                         0.284202                    0.708687

In [4]:
# Perform Merge
df = pd.merge(df, cap, left_on = 'month', right_index= True).rename(columns={
    'adult_icu_bed_covid_utilization': 'ICU_occupancy',
    'inpatient_beds_utilization': 'inpatient__occupancy'
})
df

,cdc_report_dt,pos_spec_dt,onset_dt,current_status,sex,age_group,Race and ethnicity (combined),hosp_yn,icu_yn,death_yn,medcond_yn,month,ICU_occupancy,inpatient__occupancy
0,2020/11/14,2020/11/10,2020/11/10,Laboratory-confirmed case,1.0,10 - 19 Years,Black,0.0,0.0,0.0,0.0,11,0.284202,0.708687
1,2020/11/19,2020/11/10,2020/11/09,Laboratory-confirmed case,1.0,10 - 19 Years,Black,0.0,0.0,0.0,0.0,11,0.284202,0.708687
2,2020/11/13,2020/11/10,2020/11/10,Laboratory-confirmed case,1.0,10 - 19 Years,Black,0.0,0.0,0.0,1.0,11,0.284202,0.708687
3,2020/11/09,2020/11/10,2020/11/09,Laboratory-confirmed case,1.0,10 - 19 Years,Black,0.0,0.0,0.0,0.0,11,0.284202,0.708687
4,2020/11/06,2020/11/10,2020/11/06,Laboratory-confirmed case,1.0,10 - 19 Years,Black,0.0,0.0,0.0,1.0,11,0.284202,0.708687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350457,2020/02/17,2020/03/30,2020/02/17,Laboratory-confirmed case,0.0,20 - 29 Years,Hispanic,0.0,0.0,0.0,1.0,2,NaN,0.518818
350464,2020/02/29,2020/03/30,2020/02/29,Laboratory-confirmed case,0.0,20 - 29 Years,Hispanic,1.0,1.0,0.0,0.0,2,NaN,0.518818
351045,2020/02/29,2020/04/08,2020/02/29,Laboratory-confirmed case,1.0,20 - 29 Years,Hispanic,0.0,0.0,0.0,0.0,2,NaN,0.518818
384576,2020/02/11,2020/07/10,2020/02/11,Laboratory-confirmed case,0.0,60 - 69 Years,White,0.0,0.0,0.0,0.0,2,NaN,0.518818
438871,2020/02/27,2020/03/11,2020/02/27,Laboratory-confirmed case,1.0,0 - 9 Years,White,0.0,0.0,0.0,0.0,2,NaN,0.518818

In [5]:
df.to_csv('clean_data.csv')